In [1]:
# import libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# data set load
df = pd.read_csv("../data/hospital_patient_records_cleaned.csv")
df.head()
df.tail()
#df.isnull().sum()
#df.shape

,Patient_ID,Age,Gender,BMI,Blood_Pressure,Heart_Rate,Cholesterol,HbA1c,Blood_Glucose,Creatinine,...,Smoking,Alcohol,Exercise_Hours,Hypertension,Family_History,Diabetes,Heart_Disease,Stroke,Kidney_Disease,Liver_Disease
1499,1500,35,Male,39.0,110,112,155,8.6,116.0,0.53,...,1,0,6.3,0,0,1,0,0,1,0
1500,815,73,Female,60.0,106,97,180,8.8,135.0,1.29,...,0,1,2.4,0,0,1,1,0,1,0
1501,310,83,Female,18.8,185,98,335,4.2,72.0,2.29,...,0,0,5.3,1,1,0,1,1,1,0
1502,215,68,Male,60.0,163,59,202,6.8,174.0,1.46,...,0,0,1.4,1,1,1,1,1,1,0
1503,131,76,Female,39.8,91,54,112,4.7,231.0,2.73,...,1,1,2.5,0,0,1,1,0,1,1

In [3]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1504 entries, 0 to 1503
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      1504 non-null   int64
 1   Age             1504 non-null   int64
 2   Gender          1504 non-null   str
 3   BMI             1504 non-null   float64
 4   Blood_Pressure  1504 non-null   int64
 5   Heart_Rate      1504 non-null   int64
 6   Cholesterol     1504 non-null   int64
 7   HbA1c           1504 non-null   float64
 8   Blood_Glucose   1504 non-null   float64
 9   Creatinine      1504 non-null   float64
 10  Hemoglobin      1504 non-null   float64
 11  Smoking         1504 non-null   int64
 12  Alcohol         1504 non-null   int64
 13  Exercise_Hours  1504 non-null   float64
 14  Hypertension    1504 non-null   int64
 15  Family_History  1504 non-null   int64
 16  Diabetes        1504 non-null   int64
 17  Heart_Disease   1504 non-null   int64
 18  Stroke          1504 non-null   int64
 19  Kidney_Disease  1504 non-null   int64
 20  Liver_Disease   1504 non-null   int64
dtypes: float64(6), int64(14), str(1)
memory usage: 246.9 KB

,Patient_ID,Age,BMI,Blood_Pressure,Heart_Rate,Cholesterol,HbA1c,Blood_Glucose,Creatinine,Hemoglobin,Smoking,Alcohol,Exercise_Hours,Hypertension,Family_History,Diabetes,Heart_Disease,Stroke,Kidney_Disease,Liver_Disease
count,1504.000000,1504.000000,1504.000000,1504.000000,1504.000000,1504.000000,1504.000000,1504.000000,1504.000000,1504.000000,1504.000000,1504.000000,1504.000000,1504.000000,1504.00000,1504.000000,1504.000000,1504.000000,1504.000000,1504.000000
mean,749.482048,53.686170,29.500665,137.668883,82.041888,223.888298,8.156184,177.504654,2.066742,12.819681,0.501330,0.512633,4.062367,0.484043,0.47008,0.949468,0.813165,0.153590,0.979388,0.245346
std,433.246619,20.559892,7.936546,29.997550,19.142154,65.770743,2.216316,76.719707,0.999120,2.990753,0.500165,0.500007,2.305037,0.499912,0.49927,0.219113,0.389909,0.360676,0.142128,0.430435
min,1.000000,18.000000,16.100000,85.000000,50.000000,110.000000,4.200000,65.000000,0.400000,7.500000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,373.750000,36.000000,22.900000,111.750000,65.750000,170.000000,6.300000,119.000000,1.190000,10.300000,0.000000,0.000000,2.100000,0.000000,0.00000,1.000000,1.000000,0.000000,1.000000,0.000000
50%,749.500000,54.000000,29.300000,139.000000,82.000000,226.000000,8.200000,174.000000,2.025000,12.800000,1.000000,1.000000,4.000000,0.000000,0.00000,1.000000,1.000000,0.000000,1.000000,0.000000
75%,1124.250000,71.000000,35.500000,163.000000,98.250000,279.000000,10.000000,228.000000,2.930000,15.300000,1.000000,1.000000,6.000000,1.000000,1.00000,1.000000,1.000000,0.000000,1.000000,0.000000
max,1500.000000,90.000000,60.000000,190.000000,115.000000,340.000000,12.000000,677.000000,3.790000,18.000000,1.000000,1.000000,8.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000

In [4]:
# show columns python list
df.columns.tolist()

['Patient_ID',
 'Age',
 'Gender',
 'BMI',
 'Blood_Pressure',
 'Heart_Rate',
 'Cholesterol',
 'HbA1c',
 'Blood_Glucose',
 'Creatinine',
 'Hemoglobin',
 'Smoking',
 'Alcohol',
 'Exercise_Hours',
 'Hypertension',
 'Family_History',
 'Diabetes',
 'Heart_Disease',
 'Stroke',
 'Kidney_Disease',
 'Liver_Disease']

In [5]:
# Step 1: Features (X) and Target (y)
# Remove unnecessary column and target column from features
X = df.drop(columns=["Patient_ID","Kidney_Disease"])
# Target variable
y = df["Kidney_Disease"]

In [7]:
# Step 2: Apply LabelEncoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X["Gender"] = le.fit_transform(X["Gender"])
X["Smoking"] = le.fit_transform(X["Smoking"])
X["Alcohol"] = le.fit_transform(X["Alcohol"])

In [10]:
# Step 3: Train-Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
# Step 4 : Apply Standarscaler

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
# Step 5 : Cross Validation

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

models = {
    "LR": LogisticRegression(random_state=42,max_iter=1000,class_weight="balanced"),
    "DT": DecisionTreeClassifier(random_state=42),
    "RF": RandomForestClassifier(random_state=42,    class_weight="balanced"),
    "KNN": KNeighborsClassifier(),
    "SVM": SVC(),
    "XGBoost": XGBClassifier(random_state=42, eval_metric="logloss")
}

from sklearn.model_selection import cross_val_score

for name, model in models.items():

    print(name)
    print("Accuracy :", cross_val_score(model, X_train, y_train, cv=5).mean())
    print("F1 Score :", cross_val_score(model, X_train, y_train, cv=5, scoring="f1").mean())
    print("ROC-AUC  :", cross_val_score(model, X_train, y_train, cv=5, scoring="roc_auc").mean())
    print("----------------------")

LR
Accuracy : 0.9916804979253111
F1 Score : 0.9957098508088423
ROC-AUC  : 0.9996595744680852
----------------------
DT
Accuracy : 0.9991701244813278
F1 Score : 0.9995753715498938
ROC-AUC  : 0.9833333333333334
----------------------
RF
Accuracy : 0.9933575380359614
F1 Score : 0.9966226507648805
ROC-AUC  : 1.0
----------------------
KNN
Accuracy : 0.985027662517289
F1 Score : 0.992318219266485
ROC-AUC  : 0.9961589133309292
----------------------
SVM
Accuracy : 0.9908506224066389
F1 Score : 0.9953235969591361
ROC-AUC  : 0.998468085106383
----------------------
XGBoost
Accuracy : 0.9991701244813278
F1 Score : 0.9995753715498938
ROC-AUC  : 0.9998581560283688
----------------------

In [13]:
# Step 6 : Train Best Model
from sklearn.svm import SVC
best_model = SVC(probability=True,random_state=42)
best_model.fit(X_train, y_train)

SVC(probability=True, random_state=42)

In [14]:
# Step 7 : Prediction

y_pred = best_model.predict(X_test)

In [15]:
# Step 8 : accuracy

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

Accuracy : 0.9867109634551495

In [16]:
# Step 9: Confusion Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[  2   2]
 [  2 295]]

In [17]:
# Step 10 : Model Evaluation (Classification Report)
# (Precision, Recall, F1-score, Support)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50         4
           1       0.99      0.99      0.99       297

    accuracy                           0.99       301
   macro avg       0.75      0.75      0.75       301
weighted avg       0.99      0.99      0.99       301

In [19]:
# Step 11: Save Kidney Model
import joblib

# Save trained kidney model
joblib.dump(best_model,"kidney_model.pkl")

['kidney_model.pkl']

In [20]:
# Save stroke scaler
joblib.dump(scaler,"kidney_scaler.pkl")

['kidney_scaler.pkl']